### PR TITLE
Issue #2572119: Update DataListItemAdd action to use doExecute().

### PR DESCRIPTION
**Pull request by shahinam**
Update actions & conditions to use doExecute / doEvaluate (https://www.drupal.org/node/2572119)

Updated DataListItemAdd action to use doExecute().

### CODE REVIEW

**Comment by shahinam** [comment]
Build failing for PHP:5.5 / Drupal:8.0.x only. Someone has any idea!

The build was passing - then I fixed some code formatting issues. Seems something has gone into core after that. Need to verify.

The test that is failing is:
Drupal\Tests\rules\Functional\UiPageTest::testCreateReactionRule
Current response status code is 403, but 200 expected.

**Comment by shahinam** [comment]
With my local test setup with PHP:5.5 and D:8.0.x - everything is green.

**Comment by shahinam** [comment]
Triggering build...

**Comment by klausi** [comment]
merged, thanks!

**Pull request closed without merging**
