### PR TITLE
Clean up the documentation blocks.

### PR DESCRIPTION
**Pull request by bartfeenstra**
FIX ALL THE THINGS.

### CODE REVIEW

**Comment by fubhy** [comment]
Are those changes according to CS? My Drupal CS knowledge is a bit rusty (didn't do much core lately).

**Comment by bartfeenstra** [comment]
Yes. We don't need descriptions for @return $this, as this is 
self-explanatory (it _always_ returns the object the method is called 
on). I fixed some spelling errors, and rephrased some comments a bit. 
Interfaces don't actually provide things, but define them.

**Comment by fubhy** [comment]
If "this is self-explanatory" would be enforced all across core our CD for comments would like rather differently :P. (I hate how we keep documenting absolutely redundant stuff).

**Comment by bartfeenstra** [comment]
I don't know what you mean, but @return $this without a description is 
part of the coding standards.

**Comment by fubhy** [comment]
Yeah, I meant other things. We tend to over-document self-explanatory @vars and constructor arguments and things like that... Not part of this here though.

**Pull request merged**
