### PR TITLE
Port rules init system event to D8

### PR DESCRIPTION
**Pull request by stephenpurkiss**
Hi,

I've had a quick go at starting on this - I've copied from what's been done so far but not entirely sure I got it right. From what I gather we're exposing symfony event through Drupal so perhaps this needs to link to the kernel.request event listed in rules.rules.events.yml, but I'm not sure how to do that...!

### CODE REVIEW

**Comment by bojanz** [comment]
hook_init() doesn't actually exist anymore: https://www.drupal.org/node/2013014

**Comment by klausi** [comment]
Yes, it should be enough to specify the event in the rules.rules_events.yml file since that hook is an event already :-)

**Comment by stephenpurkiss** [comment]
Thanks, I kinda had a feeling that might be the case but as it was listed as a "to-do", I did. Feel free to close this and destroy the code in a mighty flash!

**Comment by stephenpurkiss** [comment]
Oh look, there's a close button there, I have the power!

**Pull request closed without merging**
