### PR TITLE
Added PHPCS to .travis.yml.

### PR DESCRIPTION
**Pull request by jibran**

### CODE REVIEW

**Comment by jibran** [comment]
PHPCS changes are green only coding error is remaining. Do I have to fix it here?

**Comment by klausi** [comment]
This is a very cool idea! I'm not sure if Coder Sniffer is mature enough to not cause many false positives though. I'm in favor of having such a check in the Travis continuous integration, not sure if @fubhy and @fago agree?

Let's create a separate pull request for the outstanding coding standard fixes. And could you squash the commits into one here?

**Comment by jibran** [comment]
I'll fix it once #87 is in.

**Comment by jibran** [comment]
Done.

**Comment by fubhy** [comment]
Sorry for the late answer. Was on vacation :)...

Yep, I am all +1 on adding PHPCS. However, I also agree that we should not cover up any bugs in Coder but instead fix them upstream. So yeah... What @klausi said essentially...

**Comment by jibran** [comment]
So merge please :)

**Comment by fubhy** [comment]
It's still failing, so we gotta fix those failures upstream first :)

https://travis-ci.org/fago/rules/jobs/29828128

**Comment by jibran** [comment]
#92 will fix it.

**Comment by jibran** [comment]
Can some one retest it?

**Comment by fubhy** [comment]
Triggered

**Comment by klausi** [comment]
I think we should put this on hold until Coder Sniffer is more mature. There are a couple of uncertainties and false positives currently, so I would not put this into the Travis testing just yet.

**Comment by fubhy** [comment]
Any news on this Klaus? Is there anything we can help you with in terms of Coder?

**Comment by klausi** [comment]
There are still lots of false positives in Coder where we don't even have issues yet. You can help by running Coder Sniffer on Rules or Drupal core and filing issues whenever Coder spits out errors although the code is correct.

One example would be doc annotations that are allowed to exceed the 80 chars line limit in comments.

**Comment by klausi** [comment]
Closing, we can reopen once Coder is more stable for D8.

**Pull request closed without merging**
