### PR TITLE
Issue #2574521: doEvaluate for rules_entity_field_access

### PR DESCRIPTION
**Pull request by torenware**
Tests run clean w/o modification once #2573823, since the test scrambles the context.

Drupal Issue: https://www.drupal.org/node/2574521

### CODE REVIEW

**Comment by torenware** [comment]
This is still blocked by #237 (https://www.drupal.org/node/2573823).

Any chance we can get that taken care of?  Thanks!

**Comment by torenware** [comment]
I've applied phpcs to the condition, as described in the d.o. instructions.  No errors now.

**Comment by klausi** [comment]
Looks like you are reverting stuff in this pull request? Please rebase on 8.x-3.x.

**Comment by klausi** [comment]
Pushed a modified version of this with improved comments.

**Pull request closed without merging**
